POST http://localhost:3000/api/posts/2/comments
Content-Type: application/json

{
  "nickname": "별칭10",
  "content": "답글10",
  "password": "kky1212"
}

###

GET http://localhost:3000/api/posts/2/comments?page=1&pageSize=10

### 

GET http://localhost:3000/api/posts/2/comments?page=1&pageSize=10

###

PUT http://localhost:3000/api/comments/6
Content-Type: application/json

{
  "nickname": "별칭1",
  "content": "수정 댓글",
  "password": "kky1212"
}

###

DELETE http://localhost:3000/api/comments/6
Content-Type: application/json

{
  "password": "kky1212"
}
