POST http://localhost:3000/api/groups/2/posts
Content-Type: application/json

{
	"nickname": "별명6",
	"title": "제목6",
	"content": "내용6",
	"postPassword": "rkddus12",
	"groupPassword": "kky1212",
	"imageUrl": "http://www.example2.com",
	"tags": [ "string", "string" ],
	"location": "위치",
	"moment": "2024-02-21",
	"isPublic": true
}

###

# groupId 그룹의 ID, page 페이지 번호, pageSize 페이지당 게시글 수 (기본값: 10), sortBy 정렬 기준 (기본값: latest)
# keyword : string (선택) - 검색어 (제목이나 태그에 포함된 검색어), isPublic 공개 여부

# 정렬 기준 설정
# latest 최신순
# mostCommented 답글 많은순
# mostLiked 공감순
GET http://localhost:3000/api/groups/1/posts

###

GET http://localhost:3000/api/groups/1/posts?page=1&pageSize=10&sortBy=latest&isPublic=true

###

PUT http://localhost:3000/api/posts/1
Content-Type: application/json

{
	"nickname": "kangyeon1",
	"title": "제목2-1",
	"content": "내용2-1",
	"postPassword": "rkddus12",
	"imageUrl": "http://www.example1.com",
	"tags": [ "string1", "string2" ],
	"location": "위치2-1",
	"moment": "2024-02-22",
	"isPublic": false
}

###

DELETE http://localhost:3000/api/posts/3
Content-Type: application/json

{
	"postPassword": "rkddus12"
}

###

GET http://localhost:3000/api/posts/1

###

POST http://localhost:3000/api/posts/1/verify-password
Content-Type: application/json

{
	"password": "rkddus12"
}

###

POST http://localhost:3000/api/posts/1/like

###

GET http://localhost:3000/api/posts/1/is-public